# **Concatenación de arreglos**


La concatenación, o unión de dos arreglos en NumPy, se realiza principalmente a través de la función `concatenate`:

In [ ]:
#Concatenación de listas
x = [1, 2, 3]

y = [4, 5, 6]

x + y

[1, 2, 3, 4, 5, 6]

In [ ]:
#Concatenación en python
import numpy as np

xa = np.array(x)
ya = np.array(y)

np.concatenate([xa,ya])

array([1, 2, 3, 4, 5, 6])

Podemos concatenar más de dos arreglos al tiempo:

In [ ]:
za = np.array([7 , 8 , 9])

np.concatenate([xa,ya,za])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

`concatenate` también se puede usar para arreglos bidimensionales. Recuerde que las filas corresponden al eje 1 (axis = 1) y las columnas al eje 0 (axis = 0)


<p><img alt="Colaboratory logo" height="300px" src="https://i.imgur.com/KYPgvhf.png" align="left" hspace="10px" vspace="0px"></p>

In [ ]:
a = np.arange(8,14).reshape(3,2)
a

array([[ 8,  9],
       [10, 11],
       [12, 13]])

In [ ]:
np.concatenate([a,a],axis = 0)

array([[ 8,  9],
       [10, 11],
       [12, 13],
       [ 8,  9],
       [10, 11],
       [12, 13]])

Si queremos realizar la concatenación a lo largo del eje 1, debemos especificar el eje por medio de un argumento por palabra clave:

In [ ]:
np.concatenate([a,a],axis = 1)

array([[ 8,  9,  8,  9],
       [10, 11, 10, 11],
       [12, 13, 12, 13]])

La función `vstack()` es equivalente a la concatenación a lo largo del primer eje (axis=0). Al igual que `concatenate()`, recibe como argumento una secuencia de arreglos que, en este caso, deben tener la misma forma a lo largo de todos los ejes, excepto el primero. Los arreglos unidimensionales deben tener la misma longitud:

In [ ]:
# dimensiones mixtas
a = np.array([1, 2, 3])
b = np.array([[3, 4, 5],
              [6, 7, 8]])

print(a.shape, b.shape)
np.vstack([a,b])

(3,) (2, 3)


array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a = np.array([[1],
              [2]])
b = np.array([[3],
              [4],
              [5]])


print(a.shape, b.shape)
np.vstack([a,b])

(2, 1) (3, 1)


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
#No se puede hacer si presentan dimensionalidad diferente
a = np.array([1,2,3])
b = np.arange(4,8)

print(a.shape, b.shape)
try:
  np.vstack([a,b])
except Exception as e:
  print(e)

(3,) (4,)
all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4


Similarmente, la función `hstack()` realiza una concatenación a lo largo del segundo eje (axis=1), y los arreglos que toma como argumento deben coincidir en la forma a lo largo de este eje. Los arreglos unidimensionales pueden ser de cualquier longitud

In [ ]:
#dimensiones mixtas
a = np.array([[ 1, 2],
              [ 3, 4]])
b = np.arange(5,11).reshape(2,3)

print(a.shape, b.shape)
np.hstack([a,b])

(2, 2) (2, 3)


array([[ 1,  2,  5,  6,  7],
       [ 3,  4,  8,  9, 10]])

In [ ]:
#arreglos unidimensionales
a = np.array([1,2,3])
b = np.arange(4,8)

print(a.shape, b.shape)
np.hstack([a,b])

(3,) (4,)


array([1, 2, 3, 4, 5, 6, 7])

<p><a name="ind"></a></p>

# **Indexación y segmentación**

Los arreglos de NumPy tienen la misma semántica de indexación y segmentación que las listas de Python cuando se trata de acceder a elementos o subarreglos.




In [ ]:
a = np.arange(8)

print(f"a: {a}")
print()
print(f"a[3]: {a[3]}")
print()
print(f"a[2:6]: {a[2:6]}")

a: [0 1 2 3 4 5 6 7]

a[3]: 3

a[2:6]: [2 3 4 5]


Debido a que los arreglos de NumPy son n-dimensionales, podemos segmentar a lo largo de todos y cada uno de los ejes. Consideremos la siguiente lista de listas en Python

In [ ]:
# definiendo una lista de listas de forma (3,3)
L = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Por ejemplo, si queremos crear una lista de Python que contenga todas las filas y las primeras dos columnas de la lista L podríamos escribir

In [ ]:
[l[:2] for l in L]

[[1, 2], [4, 5], [7, 8]]

El número de ciclos `for` anidados que se necesita para segmentar listas de listas es igual al número de dimensiones menos uno (en este caso $2-1=1$).

En NumPy, en lugar de indexar por un segmento, podemos indexar por una tupla de segmentos, cada uno de los cuales actúa en sus propias dimensiones. Definamos el arreglo `L` con NumPy y realicemos la segmentación anterior:


In [ ]:
L = np.arange(1,10).reshape(3,3)
L

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
L[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

Los ciclos `for` para la segmentación multidimensional son manejados implícitamente por NumPy. Esto hace que realizar segmentaciones complejas sea mucho más rápido que escribir los ciclos `for` explícitamente en Python. Veamos algunos ejemplos:

In [ ]:
#creamos un arreglo de dimensiones 4x4
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
#seleccionar la primer fila (equivalente a a[0,:])
a[0]

array([0, 1, 2, 3])

In [ ]:
# seleccionar la primera columna
a[:,0]

array([ 0,  4,  8, 12])

In [ ]:
#segmentar las filas pares y las columnas impares.
a[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
#segmentar la matriz interna de 2x2.
a[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
#invertir las primeras 3 filas, tomando las primeras 3 columnas
a[2::-1, :3]

array([[ 8,  9, 10],
       [ 4,  5,  6],
       [ 0,  1,  2]])

**Ejercicio 1**: Escriba un programa para crear un nuevo arreglo que sea el promedio de cada triplete consecutivo de elementos del siguiente arreglo

<p><img alt="Colaboratory logo" height="70px" src="https://i.imgur.com/XoHovZd.png" align="left" hspace="10px" vspace="0px"></p>

In [ ]:
a = np.array([1,2,3,2,4,6,1,2,12,0,-12,6])
a = a.reshape(4,3)
np.mean(a, axis = 1)

array([ 2.,  4.,  5., -2.])

In [ ]:
 d1=np.array([1,2,3,2,4,6,1,2,12,0,-12,6])

#print(d1)
d2=d1.reshape(4,3)
#print(d2)
d3=[np.mean(d2[0:]) for d2 in d2]
print(d3)

[2.0, 4.0, 5.0, -2.0]


<p><a name="enm"></a></p>

## **Enmascaramiento**

El enmascaramiento aparece cuando deseamos extraer, modificar, o manipular valores en un arreglo de acuerdo con algún criterio.

Ya vimos cómo utilizar ufuncs para operaciones aritméticas básicas y otro tipo de operaciones más complejas. NumPy implementa también operadores de comparación como ufuncs:

In [ ]:
x = np.arange(0,9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
x < 6

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

El resultado es un arreglo booleano. Dado un arreglo booleano, hay una serie de operaciones útiles que podemos implementar.

Podemos utilizar la función `np.sum` junto con los operadores de comparación para realizar conteos dentro del arreglo:

In [ ]:
# numero de elementos menores a 6
np.sum(x < 6)

6

Con `np.sum` podemos realizar este tipo de conteos a lo largo de las filas o columnas, utilizando el argumento por palabra clave `axis`:

In [ ]:
# numero de elementos menores a 6 por columna
np.sum(x < 6, axis = 0)

array([2, 2, 2])

In [ ]:
# numero de elementos menores a 6 por fila
np.sum(x < 6, axis = 1)

array([3, 3, 0])

Podemos también tener múltiples condiciones en un conteo, utilizando los operadores lógicos `&` (and) y `|` (or)

In [ ]:
# verdadero si ambos verdaderos
np.sum((x > 1) & (x < 5 ))

3

In [ ]:
# verdadero en caso en que alguno de los dos sea verdadero
np.sum((x > 6) | (x < 2 ))

4

Una herramienta muy poderosa es usar los arreglos booleanos como máscaras, para seleccionar subconjuntos particulares de los datos mismos.

Volviendo a nuestra arreglo `x` anterior, supongamos que queremos un arreglo de todos los valores en `x` que sean menores que, digamos, 5. Para seleccionar estos valores del arreglo, simplemente podemos indexar con este arreglo booleano; esto se conoce como una operación de enmascaramiento:

In [ ]:
x = np.arange(1,10)
np.sum(x)

45

In [ ]:
np.prod(x)

362880

In [ ]:
x [ x < 6 ]

array([1, 2, 3, 4, 5])

Lo que se devuelve es un arreglo unidimensional con todos los valores que cumplen la condición; en otras palabras, todos los valores en las posiciones en las que el arreglo de máscara es `True`.

**Ejercicio 2:** Escriba una función que, dado un número entero `n`, muestre:

* Un arreglo con los primeros números pares hasta `n`.
* Un arreglo con los primeros números múltiplos de tres hasta `n`.

In [ ]:
def F(n):
  a = np.arange(1,n+1)
  pares = a[a % 2 == 0]
  mult = a[a % 3 == 0]
  print(f'pares: {pares}')
  print(f'multiplos de tres: {mult}')

F(24)

pares: [ 2  4  6  8 10 12 14 16 18 20 22 24]
multiplos de tres: [ 3  6  9 12 15 18 21 24]


**Ejercicio 3:** Escribir un programa que lea `n` números enteros, calcule y muestre la suma de los pares y el producto de los impares.

In [ ]:
def F(n):
    a = np.array(n).astype(int)
    pares = a[a % 2 == 0]
    imp = a[a % 2 != 0]
    print(f"suma de pares: {np.sum(pares)}")
    print(f"multiplicación de impares: {np.prod(imp)}")

lista = []
entrada = input("Separe con una coma los enteros a operar: ")
lista = entrada.split(",")
print(lista)

F(lista)

Separe con una coma los enteros a operar: 1,2,3,4,5,6,7,8,9,10
['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']
suma de pares: 30
multiplicación de impares: 945


In [ ]:
n = int(input("¿Cuántos números va a agregar?\n"))
print('Ingrese los números ')
N = np.array([int(input()) for i in range(n)])

print(f"Suma de entradas pares: {np.sum(N[N%2==0])}")
print(f"Producto de entradas impares: {np.prod(N[N%2!=0])}")

¿Cuántos números va a agregar?
4
Ingrese los números 
1
2
3
4
Suma de entradas pares: 6
Producto de entradas impares: 3


In [ ]:
import numpy as np

num_enteros = int(input("¿Cuántos números va a agregar?\n->"))

a = np.zeros(num_enteros)

i=0
while i < num_enteros:
    a[i] = int(input("Ingrese un número:\n->"))
    i+=1

print(f"Ha ingresado los números: {a}")
print(f"Suma de entradas pares: {np.sum(a[a%2==0])}")
print(f"Producto de entradas impares: {np.prod(a[a%2!=0])}")

<p><a name="sof"></a></p>

# **Indexación sofisticada**

Anteriormente vimos cómo acceder y modificar porciones de arreglos usando índices simples (por ejemplo, `arr[0]`), segmentos (por ejemplo, `arr[: 5]`) y máscaras booleanas (por ejemplo, `arr[arr> 0]`). Veremos ahora otro estilo de indexación de arreglos, conocido como *indexación sofisticada*, la cual nos permite acceder y modificar muy rápidamente subconjuntos complicados de los valores de un arreglo.

La indexación sofisticada es conceptualmente simple: significa pasar una lista de índices en lugar de un entero, para acceder a múltiples elementos del arreglo a la vez. Veamos un ejemplo:

In [ ]:
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.array([a[1], a[3], a[7]])

array([11, 13, 17])

In [ ]:
# creamos lista con los indices
indices = [1, 2, 3]

# accedemos a los valores del arreglo
a[indices]

array([11, 12, 13])

Con el indexado sofisticado, la forma del resultado refleja la forma del arreglo de índices más que la forma del arreglo que se está indexando:

In [ ]:
a = np.arange(0,91,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# creamos arreglo de indices con forma (2,2)
indi = np.array([[3, 7],
                 [4, 5]])

# accedemos a los valores del arreglo
a[indi]

array([[30, 70],
       [40, 50]])

El indexado sofisticado funciona también en múltiples dimensiones. Veámoslo en el siguiente ejemplo:

In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Como en la indexación estándar, el primer índice hace referencia a las filas y el segundo a las columnas:

In [ ]:
fila = [0, 1, 2]
colu = [2, 1, 3]

a[fila,colu]


array([ 2,  5, 11])

Los valores el en arreglo corresponden a `a[0,2]`, `a[1,1]` y `a[2,3]` respectivamente.