# **Memoria e iteraciones**
La implementación estándar de Python está escrita en C. Esto significa que cada objeto de Python es simplemente una estructura de C, que contiene no solo su valor, sino también otra información. Podríamos resumir que la memoria en C (que no es tema referente a este curso) hae que las variables funcionen como casilleros en los cuales guardamos valores.

![variables in C](https://i.imgur.com/0RQOTQ0.png)

En ese sentido, el casillero es reconocido por la memoria RAM del dispositivo como `0x7f1`, en dicho casillero se almacena el valor `2337` y además a este casillero se le permite tener un alias que es el nombre de la variable, en este caso `X`.

En python es un poco más complejo, pues las variables en python son punteros, que pueden ser pensadas como carteles. Por decirlo de alguna forma, todos los objetos básicos de python tales y como lo son los `int`, `str`, `bool` y en principio los `float` ya están "pre-guardados" en memoria, y al asignar una variable `X`, que almacenará el número `2337`, lo que sucede es que en memoria, el cartel pre-guardado con dicho número, y además su tipo, ahora tendrá una referencia de conteo.

![](https://i.imgur.com/F3IQqwE.png)

Lo anterior tiene un gran número de consecuencias en cómo funcionan las variables y muy especialmente las estructuras tales como las listas en python. Una de dichas consecuencias, de la que queremos hablar en esta ocasión es la forma en la que itera python.

Las estructuras en python pueden ser heterogeneas. Esto quiere decir que las estructuras, pueden almacenar diferentes tipos de variables en ellas.

In [ ]:
l_hetero = [0, 1.0, 2.0j , "tres", [4, {5}]]

for element in l_hetero:
  print(type(element))

<class 'int'>
<class 'float'>
<class 'complex'>
<class 'str'>
<class 'list'>


In [ ]:
print(type(l_hetero))

<class 'list'>


En esta iteración se puede ver casi de manera plausible qué es lo que pasa con a iteración sobre este tipo de estructuras. Cuando Python itera a través de ellas, tiene que comprobar qué tipo de objeto es, y cuáles son sus posibilidades en términos de métodos y atributos. Lo cual hace que la iteración sea altamente costosa.

Una solución ampliamente usada por la comunidad es el uso de un módulo llamado `Numpy`. Aunque existen alternativas con mejor manejo de memoria a Numpy como `Pandas`, `Awkward` o `ROOT` (que más que ser un módulo es un ecosistema completo) la mayoría son generalizaciones de `Numpy` y tienen de fondo mucho de la filosofía de numpy trás de si. El truco con `Numpy` es el generar un tipo de estructuras homogeneas, las cuales facilitan la iteración.

<p><img alt="Colaboratory logo" height="350px" src="https://i.imgur.com/8EbyB0c.png" align="left" hspace="10px" vspace="0px"></p>

# **Numpy y ndarrays**

Al nivel de implementación, un arreglo de numpy contiene esencialmente un puntero único a un bloque contiguo de datos. La lista de Python, por otro lado, contiene un puntero a un bloque de punteros, cada uno de los cuales a su vez apunta a un objeto completo de Python como el entero de Python que vimos anteriormente.

En resumen, estas son las diferencias más importantes entre los arreglos de NumPy y las secuencias estándar de Python:

* Todos los elementos en un arreglo de NumPy deben ser del mismo tipo de dato y, por lo tanto, tendrán el mismo tamaño en memoria.
* Los arreglos de NumPy tienen un tamaño fijo en la creación, a diferencia de las listas de Python (que pueden crecer dinámicamente). Cambiar el tamaño de un `ndarray` creará un nuevo arreglo y eliminará el original.
* Los arreglos de NumPy facilitan operaciones avanzadas matemáticas y de otro tipo en grandes cantidades de datos. Típicamente, tales operaciones se ejecutan de manera más eficiente que usando las secuencias integradas de Python.

Veamos cómo definir arreglos de numpy

In [ ]:
import numpy as np

#En el caso que solo se desdee traer array el comando sería from numpy import array
#JAMÁS USAR from numpy import *

In [ ]:
arr = np.array([1, 2, 3])
print(type(arr), arr)

<class 'numpy.ndarray'> [1 2 3]


## **dtype**:
A primera vista, no existe mucha diferencia entre una lista nativa de Python y un arreglo de Numpy. Pero podemos empezar a explorar las diferencias a partir de uno de los atributos de los arreglos.


In [ ]:
arr.dtype

dtype('int64')

Se puede ver que los arreglos poseen un atributo que caracteriza las variables que contiene dentro de él. Aunque no se hubiese establecido este atributo en la declaración, los arreglos asumen que como todas las entradas son enteros, el arreglo debe tener entradas en general de enteros de 64 bits. Si alguna de las entradas fuera un número de coma flotante, entonces el arreglo sería un arreglo de flotantes de 64 bits.

In [ ]:
arr = np.array([1, 2, 3, 4.])
print(arr.dtype, arr)

float64 [1. 2. 3. 4.]


Sin embargo el tipo puede ser definido desde la declaración.

In [ ]:
arr = np.array([1, 2, 3, 4.], dtype = "int32")
print(arr.dtype, arr)

int32 [1 2 3 4]


Los principales tipos son:

<p><img alt="Colaboratory logo" height="400px" src="https://i.imgur.com/2RpU9w1.png" align="left" hspace="10px" vspace="0px"></p>

## **shape:**

Atributo que devuelve una tupla de enteros que representa el rango a lo largo de cada dimensión de los arreglos n-dimensionales.

In [ ]:
l = [[1,2], [3,4]]
arr2 = np.array(l)
arr = np.array([1, 2, 3, 4])
arr.shape

(4,)

La forma `(4,)`, nos dice que `l` es un arreglo unidimensional, donde la dimensión tiene un rango 4. La dimensión y el número de elementos del arreglo se pueden obtener mediante los atributos `ndim` y `size`, respectivamente:

In [ ]:
arr.ndim

1

In [ ]:
arr2.size

4

In [ ]:
len(arr2)

2

Podemos modificar la forma del arreglo modificando el atributo shape:

In [ ]:
arr2.shape = (2,2)
print(arr2)

[[1 2]
 [3 4]]


In [ ]:
arr2.shape

(2, 2)

Alternativamente, NumPy proporciona el método `reshape`, con el cual podemos cambiar la forma de un arreglo. Este toma como argumento el arreglo a modificar y un entero o tupla que represente la nueva forma.

Esta nueva forma debe ser compatible con el número de elementos que tenga el arreglo. Cambiemos la forma de `l` para tener un vector fila:

In [ ]:
np.array([i for i in range(1,7)]).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

NumPy nos permite pasar una de las dimensiones como `-1`. De esta manera, Numpy se encargará de que el rango en esa dimensión sea compatible con el arreglo original y con el rango de la dimensión que se fijó:

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
arr.reshape(1,-1)

array([[1, 2, 3, 4]])

In [ ]:
arr.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4]])

## **Formas alternativas de construir arreglos:**

NumPy proporciona formas alternativas de crear arreglos. Las funciones más comunes son `arange`, `linspace` `zeros`, `ones`, `full` y `empty`.

####**Tarea**

Consultar cómo construir arreglos con números aleatorios. ¿Se puede construir un arreglo con números aleatorios que sigan una distribución normal, exponencial?

* La función `arange()` toma un inicio, final y un paso como la función `range()` de Python, excepto que devuelve un `ndarray` y que el paso puede ser un número real.

In [ ]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

- La función `linspace` crea una serie de puntos uniformemente entre un límite inferior y superior que incluye ambos extremos. Su sintáxis es de la forma:

>
    linspace(inicio, final, numero de puntos)

In [ ]:
a = np.linspace(0.5,10.5,100, endpoint= False)
a

array([ 0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,  1.2,  1.3,  1.4,  1.5,
        1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,
        2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,
        3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,
        4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9,
        6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,  6.9,  7. ,
        7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9,  8. ,  8.1,
        8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ,  9.1,  9.2,
        9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9, 10. , 10.1, 10.2, 10.3,
       10.4])

In [ ]:
np.linspace(0.5,10.5,100, retstep= True)

(array([ 0.5       ,  0.6010101 ,  0.7020202 ,  0.8030303 ,  0.9040404 ,
         1.00505051,  1.10606061,  1.20707071,  1.30808081,  1.40909091,
         1.51010101,  1.61111111,  1.71212121,  1.81313131,  1.91414141,
         2.01515152,  2.11616162,  2.21717172,  2.31818182,  2.41919192,
         2.52020202,  2.62121212,  2.72222222,  2.82323232,  2.92424242,
         3.02525253,  3.12626263,  3.22727273,  3.32828283,  3.42929293,
         3.53030303,  3.63131313,  3.73232323,  3.83333333,  3.93434343,
         4.03535354,  4.13636364,  4.23737374,  4.33838384,  4.43939394,
         4.54040404,  4.64141414,  4.74242424,  4.84343434,  4.94444444,
         5.04545455,  5.14646465,  5.24747475,  5.34848485,  5.44949495,
         5.55050505,  5.65151515,  5.75252525,  5.85353535,  5.95454545,
         6.05555556,  6.15656566,  6.25757576,  6.35858586,  6.45959596,
         6.56060606,  6.66161616,  6.76262626,  6.86363636,  6.96464646,
         7.06565657,  7.16666667,  7.26767677,  7.3

- Las funciones `zeros()` y `ones()` toman un entero o una tupla de enteros como argumento y devuelven un `ndarray` cuya forma coincide con la de la tupla y cuyos elementos son cero o uno:

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

- La función `full()` funciona de manera similar a `zeros()` y `ones()`, solo que podemos llenar el arreglo con cualquier valor:

In [ ]:
np.full((3,4), 17.5)

array([[17.5, 17.5, 17.5, 17.5],
       [17.5, 17.5, 17.5, 17.5],
       [17.5, 17.5, 17.5, 17.5]])

- La función `empty()`, por otro lado, asignará memoria sin asignarle ningún valor. Esto significa que el contenido de un arreglo vacío será lo que esté en la memoria en ese momento. Esto es particularmente útil cuando creamos un arreglo cuyos valores serán modificados posteriormente.

In [ ]:
pi = 3.14
e = 2.7
r =17.2
np.empty((5,4))

array([[0. , 0. , 0.3, 1. ],
       [0. , 0. , 1. , 1. ],
       [1. , 1. , 1. , 1. ],
       [1. , 0. , 0. , 1. ],
       [0.5, 0. , 0. , 1. ]])

<p><a name="ope"></a></p>

# **Operaciones sobre los arreglos**

Ahora que hemos visto cómo definir arreglos de NumPy, podemos discutir cómo realizar operaciones sobre los arreglos. La clave para hacer estas operaciones de una forma rápida y eficiente es usar operaciones **vectorizadas**, implementadas a través de las funciones universales de NumPy (ufuncs).

Recordemos que la operación de sumar dos listas de Python resulta en la concatenación de dichas listas:



In [ ]:
lista1 = [ 1, 2, 3, 4]
lista2 = [5, 6 ,7 , 8]

lista1 + lista2

[1, 2, 3, 4, 5, 6, 7, 8]

Si quisieramos sumar elemento a elemento, debemos hacer explícito un ciclo `for` con la función `zip()` para dos variables de la siguiente manera (ver **Apéndice A**):

In [ ]:
#forma 1

for i in range(len(lista1)):
  print(lista1[i] + lista2[i])

6
8
10
12


In [ ]:
for i,j in zip(lista1, lista2):
  print(i + j)

6
8
10
12


In [ ]:
arreglo_1 = np.array(lista1)
arreglo_2 = np.array(lista2)

arreglo_1 + arreglo_2

array([ 6,  8, 10, 12])

Si realizamos esta misma operación con arreglos de Numpy, obtendremos otra salida:

In [ ]:
np.add(lista1, lista2)

array([ 6,  8, 10, 12])

In [ ]:
np.add(arreglo_1, arreglo_2)

array([ 6,  8, 10, 12])

Como los arreglos son de NumPy, se está realizando lo que se conoce como una operación **vectorizada**, la cual es una operación sobre los arreglos que se realiza **elemento a elemento**, mediante lo que conocemos como funciones universales (ufuncs) de Numpy.

Las ufuncs de NumPy se sienten muy naturales de usar porque hacen uso de los operadores aritméticos nativos de Python.

La siguiente tabla nos muestra algunas de las funciones universales disponibles en Numpy (ver [documentación](https://numpy.org/doc/stable/reference/ufuncs.html#ufunc))







![picture](https://i.imgur.com/8HaZzxg.png)

Note que estas se muestran en dos versiones: mediante un operador y su correspondiente función universal. Por ejemplo `+` y `np.add`. Como en el ejemplo anterior, si los arreglos son de NumPy, el operador que utilicemos para realizar las operaciones representará la función universal. Si el arreglo no se define como uno de NumPy, y si queremos aplicar una función universal, debemos utilizar la forma explícita de la función universal

En el caso de la multiplicacion en Python, la multiplicación de un número entero $n$ por una lista $l$, nos arroja una lista que contiene los elementos de $l$ $n$ veces:



In [ ]:
n = 3

lista1 * n

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

Si quisieramos multiplicar el entero por cada uno de los elementos de la lista $l$ debemos incluir un ciclo for:

In [ ]:
[n * elemento for elemento in lista1]

[3, 6, 9, 12]

Además, la operación de multiplicación entre listas no está definida:

In [ ]:
try:
  lista1 * lista2
except Exception as e:
  print(e)

can't multiply sequence by non-int of type 'list'


En NumPy, ambas operaciones se hacen de forma vectorizada:

In [ ]:
n * arreglo_1

array([ 3,  6,  9, 12])

In [ ]:
np.multiply(n, lista1)

array([ 3,  6,  9, 12])

Note que ambas operaciones se hacen elemento a elemento, caracteriztica de las operaciones vectorizadas implementadas a través de ufuncs. Note además, que en el caso de la multiplicación de arreglos, la salida no corresponde a lo que conocemos como producto punto. Para realizar esta operación, tanto en arreglos unidimensionales como n-dimensionales, podemos utilizar la función universal `np.dot` o su operador asociado `@`:

In [ ]:
arreglo_1 * arreglo_2

array([ 5, 12, 21, 32])

In [ ]:
np.dot(arreglo_1 , arreglo_1)

30

In [ ]:
arreglo_1 @ arreglo_1

30

Es importante mencionar que el uso de operaciones vectorizadas no solo significa la utilización de funciones universales para la realización de las operaciones elemento a elemento.

En el contexto de lenguajes de alto nivel como Python, el término **vectorización** representa el uso de código optimizado y precompilado escrito en lenguajes de bajo nivel (por ejemplo C) para realizar operaciones matemáticas en una secuencia de datos. Esto se realiza en lugar de una iteración explicita escrita en código nativo, como ya vimos en el ejemplo de la multiplicacion, que hace que las operaciones sean más eficientes.

**Ejercicio**

Veamos un ejemplo con el cual se ilustra la eficiencia computacional que se alcanza con las operaciones vectorizadas de NumPy: Construyamos una función que calcule el recíproco de una lista

In [ ]:
def Lista_Reciprocos(lista):
  """
  Esta función calcula una lista con los recíprocos
  de los elemntos de la lista que acepta por entrada
  """
  salida = []
  for elemento in lista:
    salida.append(1/elemento)

  return salida

Lista_Reciprocos([1, 2, 3])

[1.0, 0.5, 0.3333333333333333]

In [ ]:
a = list(range(1,100000))

In [ ]:
%timeit Lista_Reciprocos(a)

100 loops, best of 5: 10.8 ms per loop


La operación equivalente en NumPy, utilizando ufuncs, será:

In [ ]:
R = np.arange(1,100000)

In [ ]:
%timeit 1/R

The slowest run took 13.13 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 5: 199 µs per loop


Note que hay tres ordenes de magnitud de diferencia en el tiempo de computo en ambas versiones.

Resulta que el cuello de botella aquí no son las operaciones en sí mismas, sino la verificación de tipos y demás que Python debe hacer en cada ciclo. Cada vez que se calcula el recíproco, Python primero examina el tipo de objeto y realiza una búsqueda dinámica de la función correcta que se utilizará para ese tipo. Si estuviéramos trabajando en código compilado, esta especificación de tipo se conocería antes de que se ejecute el código y el resultado podría calcularse de manera mucho más eficiente.

Los cálculos que usan vectorización a través de ufuncs son casi siempre más eficientes que su contraparte implementada a través de ciclos, especialmente a medida que los arreglos crecen en tamaño. Cada vez que se vea un ciclo de este tipo en Python, debe considerarse si este puede reemplazarse con una expresión vectorizada.

**Ejercicio:**  La serie de Leibniz  $$\frac{\pi}{4}=1-\frac{1}{3}+\frac{1}{5}-\frac{1}{7} -\frac{1}{9}+ \cdot \cdot \cdot=\sum_{n=0}^{\infty} \frac{(-1)^n}{2n+1}$$ La serie de Leibniz permite obtener un valor aproximado para el número $\pi$. Escriba un programa en el que dado el número de términos de la sumatoria, se calcule y muestre el valor aproximado de $\pi$.

 $$\pi=4\sum_{n=0}^{\infty} \frac{(-1)^n}{2n+1}$$

$$\sum_{n = 1}^{i} n$$

In [ ]:
def suma(n):
  return sum(i for i in range(1,n+1))

suma(100)

5050

In [ ]:
def leib(n):
  return 4*sum(((-1)**i)/(2*i+1) for i in range(0,n))

leib(100000)

3.1415826535897198

In [ ]:
def Py_numpy(m):
  n = np.arange(m+1)
  return 4 * np.sum((-1)**n/(2*n + 1))
Py_numpy(100000)

3.1416026534897927

In [ ]:
%timeit leib(100000)

10 loops, best of 5: 39.7 ms per loop


In [ ]:
%timeit Py_numpy(100000)

100 loops, best of 5: 6.81 ms per loop
